import type { LucideIcon } from "lucide-react";
import { Activity, CheckCircle2, Clock3, Database, Globe2, LockKeyhole, RefreshCw, Server, ShieldCheck, Zap } from "lucide-react";

const services: Array<[string,string,string,string,LucideIcon]> = [
  ["Admin authentication","Session validation","12 ms","Operational",LockKeyhole],
  ["Firestore","Content database","48 ms","Operational",Database],
  ["Blog API","Read / write","36 ms","Operational",Server],
  ["Career API","Read / write","42 ms","Operational",Server],
  ["Contact API","Inbox + updates","39 ms","Operational",Globe2],
];

export default function SystemPage(){return <div className="space-y-6"><div><p className="eyebrow">Observe</p><h1 className="text-2xl font-semibold tracking-[-0.04em] mt-1">System Health</h1><p className="text-xs text-white/30 mt-2">A production-style view of the services behind the admin console.</p></div><div className="card p-5 lg:p-6 data-grid"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-emerald-300 shadow-[0_0_14px_rgba(117,224,167,.7)]"/><span className="text-sm font-semibold">All systems operational</span></div><p className="text-[10px] text-white/28 mt-2">Last checked just now · Demo health data</p></div><button className="h-9 px-3 rounded-lg border border-white/[0.08] text-xs text-white/50 flex items-center gap-2"><RefreshCw size={13}/> Run checks</button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6"><Metric label="Uptime" value="99.98%"/><Metric label="Median latency" value="36 ms"/><Metric label="Requests today" value="12,842"/><Metric label="Incidents" value="0"/></div></div><div className="card overflow-hidden"><div className="px-5 py-4 border-b border-white/[0.06]"><p className="eyebrow">Service checks</p><h2 className="text-sm font-semibold mt-1">Dependencies</h2></div>{services.map(([name,desc,latency,status,Icon])=><div key={String(name)} className="flex items-center gap-4 px-5 py-4 border-b border-white/[0.05] last:border-0"><div className="w-9 h-9 rounded-xl bg-white/[0.03] flex items-center justify-center"><Icon size={15} className="text-white/30"/></div><div className="flex-1"><p className="text-xs text-white/70">{String(name)}</p><p className="text-[9px] text-white/22 mt-1">{String(desc)}</p></div><span className="hidden sm:block text-[10px] text-white/25 font-mono">{String(latency)}</span><span className="flex items-center gap-1.5 text-[9px] text-emerald-300"><span className="w-1.5 h-1.5 rounded-full bg-emerald-300"/>{String(status)}</span></div>)}</div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Card icon={Activity} title="Audit pipeline" text="All admin actions are ready to be recorded for traceability."/><Card icon={ShieldCheck} title="Credential posture" text="Service credentials stay server-side and are never exposed to the browser."/><Card icon={Zap} title="Fast path" text="Content operations are designed to stay simple and low-latency."/></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[0.06] bg-black/20 p-3"><p className="metric-value text-lg font-semibold">{value}</p><p className="text-[9px] text-white/25 mt-1">{label}</p></div>}
function Card({icon:Icon,title,text}:{icon:LucideIcon;title:string;text:string}){return <div className="card p-4"><Icon size={15} className="text-white/30"/><p className="text-xs font-medium text-white/65 mt-4">{title}</p><p className="text-[9px] leading-4 text-white/25 mt-1">{text}</p></div>}
